name: Build Jenkins swarm client container
on:
  push:
    branches:
      - main
  pull_request:

env:
  CONTAINER_NAME: jenkins-swarm-client

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: lsst-dm/build-and-push@main
        with:
          platforms: linux/amd64,linux/arm64
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          build-args: |
            JSWARM_UID=48435
            JSWARM_GID=202
          labels: runnumber=${{ github.run_id }}
